spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/fincords?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true

server:
  port: 8080
  compression:
    enabled: true

logging:
  level:
    web: DEBUG
    root: INFO
    com.fincords: DEBUG
  file:
    name: logs/fincords-dev.log
    max-size: 10MB
    max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  logstash:
    enabled: false

lombok:
  slf4j:
    simpleLogger: true

# JWT properties
jwt:
  secret: "AYKSDA13Rd3hhq41VcYGkS2alfwbe3QLPmJb9YUE1PU="
  expiration: 1200000 # 20 minutes

#Twilio variables
twilio:
  sid: AC56f3436d05f4c43f5b15875271a4e260
  token: b33dbae678dcf94fe0bb9358681cc908
  number: +12075032978

# Angular properties
angular:
  url: http://localhost:4200