spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO

app:
  name: Finance Tracker
  description: A finance tracking application between supplier and consumer
  version: 1.0.0