spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/fincords?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true

server:
  port: 8080
  compression:
    enabled: true

logging:
  level:
    web: DEBUG
    root: INFO
    com.fincords: DEBUG
  file:
    name: logs/fincords.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  logstash:
    enabled: false